export * from './easy-social-auth.service';
export * from './enums/auth-type.enum';
export * from './enums/grant-type.enum';
export * from './interfaces/config.interface';
export * from './interfaces/social-user.interface';
export * from './interfaces/easy-social-auth-response.interface';
export * from './strategies/easy-social-auth.strategy';
export * from './strategies/google.strategy';
export * from './strategies/facebook.strategy';
export * from './strategies/twitter.strategy';
export * from './strategies/instagram.strategy'
export * from './config';